/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gaurav.rao.view;

import com.gaurav.rao.initializer.MapInitializer;
import com.gaurav.rao.map.Location;
import com.gaurav.rao.map.RegionMap;
import com.gaurav.rao.model.Agent;
import com.gaurav.rao.model.AgentCatalog;
import com.gaurav.rao.stats.Wind;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Gaurav
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    RegionMap rm ; 
    List<JLabel> labels;
    AgentCatalog agentCatalog;
       
    static Wind wind;
    
    public MainJFrame(){
        initComponents();
        
        rm = new RegionMap();
        agentCatalog  = new AgentCatalog();
        labels = new ArrayList<>();
               
        initLabelList();
        initAgents();     
        
        MapInitializer.initRegionMap(rm, labels);    
        initComboBoxes();
        
        Wind.startBlowing(lblWindSpeed, lblWindDirection);
    }
    
    private void initLabelList(){
        labels.add(lblBarnstable);
        labels.add(lblCambridge);
        labels.add(lblDedham);
        labels.add(lblEdgartown);
        labels.add(lblGreenfield);
        labels.add(lblNantucket);
        labels.add(lblNorthampton);
        labels.add(lblPittsfield);
        labels.add(lblPlymouth);
        labels.add(lblPlymouth);
        labels.add(lblSalem);
        labels.add(lblSpringfield);
        labels.add(lblTaunton);
        labels.add(lblWorcester);
    }
    
    private void initAgents(){
        Agent agent1 = new Agent("Alpha", 2f, lblAgent1); 
        Agent agent2 = new Agent("Beta", 2f,lblAgent2); 
        Agent agent3 = new Agent("Gamma", 2f,lblAgent3); 
        Agent agent4 = new Agent("Delta", 2f,lblAgent4); 
        Agent agent5 = new Agent("Epsilon", 2f,lblAgent5); 
       
        agentCatalog.addAgent(agent1);
        agentCatalog.addAgent(agent2);
        agentCatalog.addAgent(agent3);
        agentCatalog.addAgent(agent4);
        agentCatalog.addAgent(agent5);
    }
    
    private void initComboBoxes(){
        cmbFrom.removeAllItems();
        
        for(Location l : rm.getLocations())
            cmbFrom.addItem(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitoringTabbedPanel = new javax.swing.JTabbedPane();
        createAgentPanel = new javax.swing.JPanel();
        cmbFrom = new javax.swing.JComboBox();
        cmbTo = new javax.swing.JComboBox();
        btnRun = new javax.swing.JButton();
        mapViewScrollPane = new javax.swing.JScrollPane();
        mapViewPanel = new javax.swing.JPanel();
        lblAgent1 = new javax.swing.JLabel();
        lblAgent2 = new javax.swing.JLabel();
        lblAgent3 = new javax.swing.JLabel();
        lblAgent4 = new javax.swing.JLabel();
        lblAgent5 = new javax.swing.JLabel();
        lblWorcester = new javax.swing.JLabel();
        lblNorthampton = new javax.swing.JLabel();
        lblPittsfield = new javax.swing.JLabel();
        lblSpringfield = new javax.swing.JLabel();
        lblSalem = new javax.swing.JLabel();
        lblDedham = new javax.swing.JLabel();
        lblTaunton = new javax.swing.JLabel();
        lblPlymouth = new javax.swing.JLabel();
        lblBarnstable = new javax.swing.JLabel();
        lblNantucket = new javax.swing.JLabel();
        lblGreenfield = new javax.swing.JLabel();
        lblEdgartown = new javax.swing.JLabel();
        lblCambridge = new javax.swing.JLabel();
        lblWindDirection = new javax.swing.JLabel();
        lblWindSpeed = new javax.swing.JLabel();
        lblMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAgentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromActionPerformed(evt);
            }
        });

        cmbTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAgentPanelLayout = new javax.swing.GroupLayout(createAgentPanel);
        createAgentPanel.setLayout(createAgentPanelLayout);
        createAgentPanelLayout.setHorizontalGroup(
            createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAgentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAgentPanelLayout.createSequentialGroup()
                        .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        createAgentPanelLayout.setVerticalGroup(
            createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAgentPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRun)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        monitoringTabbedPanel.addTab("New Agent ", createAgentPanel);

        getContentPane().add(monitoringTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 140));

        mapViewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane/black/N.png"))); // NOI18N
        lblAgent1.setToolTipText("");
        lblAgent1.setName("Agent 1"); // NOI18N
        mapViewPanel.add(lblAgent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        lblAgent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane/black/N.png"))); // NOI18N
        lblAgent2.setToolTipText("");
        lblAgent2.setName("Agent 2"); // NOI18N
        mapViewPanel.add(lblAgent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        lblAgent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane/black/N.png"))); // NOI18N
        lblAgent3.setToolTipText("");
        lblAgent3.setName("Agent 3"); // NOI18N
        mapViewPanel.add(lblAgent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        lblAgent4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane/black/N.png"))); // NOI18N
        lblAgent4.setToolTipText("");
        lblAgent4.setName("Agent 4"); // NOI18N
        mapViewPanel.add(lblAgent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        lblAgent5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane/black/N.png"))); // NOI18N
        lblAgent5.setToolTipText("");
        lblAgent5.setName("Agent 5"); // NOI18N
        mapViewPanel.add(lblAgent5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        lblWorcester.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblWorcester.setForeground(new java.awt.Color(102, 102, 102));
        lblWorcester.setText("Worcester");
        mapViewPanel.add(lblWorcester, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 90, 20));

        lblNorthampton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblNorthampton.setForeground(new java.awt.Color(102, 102, 102));
        lblNorthampton.setText("Northampton");
        mapViewPanel.add(lblNorthampton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, 20));

        lblPittsfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblPittsfield.setForeground(new java.awt.Color(102, 102, 102));
        lblPittsfield.setText("Pittsfield");
        mapViewPanel.add(lblPittsfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, 20));

        lblSpringfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblSpringfield.setForeground(new java.awt.Color(102, 102, 102));
        lblSpringfield.setText("Springfield");
        mapViewPanel.add(lblSpringfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 90, 20));

        lblSalem.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblSalem.setForeground(new java.awt.Color(102, 102, 102));
        lblSalem.setText("Salem");
        mapViewPanel.add(lblSalem, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 90, 20));

        lblDedham.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblDedham.setForeground(new java.awt.Color(102, 102, 102));
        lblDedham.setText("Dedham");
        mapViewPanel.add(lblDedham, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 90, 20));

        lblTaunton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblTaunton.setForeground(new java.awt.Color(102, 102, 102));
        lblTaunton.setText("Taunton");
        mapViewPanel.add(lblTaunton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 90, 20));

        lblPlymouth.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblPlymouth.setForeground(new java.awt.Color(102, 102, 102));
        lblPlymouth.setText("Plymouth");
        mapViewPanel.add(lblPlymouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 90, 20));

        lblBarnstable.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblBarnstable.setForeground(new java.awt.Color(102, 102, 102));
        lblBarnstable.setText("Barnstable");
        mapViewPanel.add(lblBarnstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 90, 20));

        lblNantucket.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblNantucket.setForeground(new java.awt.Color(102, 102, 102));
        lblNantucket.setText("Nantucket");
        mapViewPanel.add(lblNantucket, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 70, 20));

        lblGreenfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblGreenfield.setForeground(new java.awt.Color(102, 102, 102));
        lblGreenfield.setText("Greenfield");
        mapViewPanel.add(lblGreenfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, 20));

        lblEdgartown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblEdgartown.setForeground(new java.awt.Color(102, 102, 102));
        lblEdgartown.setText("Edgartown");
        mapViewPanel.add(lblEdgartown, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 90, 20));

        lblCambridge.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblCambridge.setForeground(new java.awt.Color(102, 102, 102));
        lblCambridge.setText("Cambridge");
        mapViewPanel.add(lblCambridge, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 90, 20));

        lblWindDirection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compass/compass.jpg"))); // NOI18N
        mapViewPanel.add(lblWindDirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 140, 140));
        mapViewPanel.add(lblWindSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 454, 140, 30));

        lblMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maps/massachusetts-county-map.png"))); // NOI18N
        lblMap.setText("  ");
        mapViewPanel.add(lblMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1130, 640));

        mapViewScrollPane.setViewportView(mapViewPanel);

        getContentPane().add(mapViewScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1150, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromActionPerformed
        
        if(cmbFrom == null){
            return;
        }
        Location from = (Location) cmbFrom.getSelectedItem();
        
        cmbTo.removeAllItems();
        for(Location l : rm.getLocations())
            cmbTo.addItem(l);
        cmbTo.removeItem(from);
        
    }//GEN-LAST:event_cmbFromActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        
            Location from = (Location)cmbFrom.getSelectedItem();
            Location to = (Location)cmbTo.getSelectedItem();
            
            Agent agent = agentCatalog.getAgent();
            if(agent == null) { 
                System.out.println("No available agent");
                return;
            }   
            agent.setSourceAndDestination(from, to);
            agent.run();
            System.out.println(agent.name() + " running !");
    }//GEN-LAST:event_btnRunActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JComboBox cmbFrom;
    private javax.swing.JComboBox cmbTo;
    private javax.swing.JPanel createAgentPanel;
    private javax.swing.JLabel lblAgent1;
    private javax.swing.JLabel lblAgent2;
    private javax.swing.JLabel lblAgent3;
    private javax.swing.JLabel lblAgent4;
    private javax.swing.JLabel lblAgent5;
    private javax.swing.JLabel lblBarnstable;
    private javax.swing.JLabel lblCambridge;
    private javax.swing.JLabel lblDedham;
    private javax.swing.JLabel lblEdgartown;
    private javax.swing.JLabel lblGreenfield;
    private javax.swing.JLabel lblMap;
    private javax.swing.JLabel lblNantucket;
    private javax.swing.JLabel lblNorthampton;
    private javax.swing.JLabel lblPittsfield;
    private javax.swing.JLabel lblPlymouth;
    private javax.swing.JLabel lblSalem;
    private javax.swing.JLabel lblSpringfield;
    private javax.swing.JLabel lblTaunton;
    private javax.swing.JLabel lblWindDirection;
    private javax.swing.JLabel lblWindSpeed;
    private javax.swing.JLabel lblWorcester;
    private javax.swing.JPanel mapViewPanel;
    private javax.swing.JScrollPane mapViewScrollPane;
    private javax.swing.JTabbedPane monitoringTabbedPanel;
    // End of variables declaration//GEN-END:variables
}
