/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gaurav.rao.view;

import com.gaurav.rao.initializer.MapInitializer;
import com.gaurav.rao.map.Location;
import com.gaurav.rao.map.RegionMap;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Gaurav
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    RegionMap rm ; 
    List<JLabel> labels;
    
    List<JLabel> availAgents;
    
    public MainJFrame(){
        initComponents();
        
        rm = new RegionMap();
        labels = new ArrayList<>();
        availAgents = new ArrayList<>();
               
        labels.add(lblBarnstable);
        labels.add(lblCambridge);
        labels.add(lblDedham);
        labels.add(lblEdgartown);
        labels.add(lblGreenfield);
        labels.add(lblNantucket);
        labels.add(lblNorthampton);
        labels.add(lblPittsfield);
        labels.add(lblPlymouth);
        labels.add(lblPlymouth);
        labels.add(lblSalem);
        labels.add(lblSpringfield);
        labels.add(lblTaunton);
        labels.add(lblWorcester);
        
        availAgents.add(lblAgent1);
        availAgents.add(lblAgent2);
        availAgents.add(lblAgent3);
        availAgents.add(lblAgent4);
        availAgents.add(lblAgent5);
        
        MapInitializer.initRegionMap(rm, labels);
        
        initComboBoxes();
    }
    
    public void initComboBoxes(){
        cmbFrom.removeAllItems();
        
        for(Location l : rm.getLocations())
            cmbFrom.addItem(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitoringTabbedPanel = new javax.swing.JTabbedPane();
        createAgentPanel = new javax.swing.JPanel();
        cmbFrom = new javax.swing.JComboBox();
        cmbTo = new javax.swing.JComboBox();
        btnRun = new javax.swing.JButton();
        mapViewScrollPane = new javax.swing.JScrollPane();
        mapViewPanel = new javax.swing.JPanel();
        lblWorcester = new javax.swing.JLabel();
        lblNorthampton = new javax.swing.JLabel();
        lblPittsfield = new javax.swing.JLabel();
        lblSpringfield = new javax.swing.JLabel();
        lblSalem = new javax.swing.JLabel();
        lblDedham = new javax.swing.JLabel();
        lblTaunton = new javax.swing.JLabel();
        lblPlymouth = new javax.swing.JLabel();
        lblBarnstable = new javax.swing.JLabel();
        lblNantucket = new javax.swing.JLabel();
        lblGreenfield = new javax.swing.JLabel();
        lblEdgartown = new javax.swing.JLabel();
        lblCambridge = new javax.swing.JLabel();
        lblAgent1 = new javax.swing.JLabel();
        lblAgent2 = new javax.swing.JLabel();
        lblAgent3 = new javax.swing.JLabel();
        lblAgent4 = new javax.swing.JLabel();
        lblAgent5 = new javax.swing.JLabel();
        lblMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAgentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromActionPerformed(evt);
            }
        });

        cmbTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAgentPanelLayout = new javax.swing.GroupLayout(createAgentPanel);
        createAgentPanel.setLayout(createAgentPanelLayout);
        createAgentPanelLayout.setHorizontalGroup(
            createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAgentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createAgentPanelLayout.createSequentialGroup()
                        .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        createAgentPanelLayout.setVerticalGroup(
            createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAgentPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(createAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRun)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        monitoringTabbedPanel.addTab("New Agent ", createAgentPanel);

        getContentPane().add(monitoringTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 140));

        mapViewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWorcester.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblWorcester.setForeground(new java.awt.Color(102, 102, 102));
        lblWorcester.setText("Worcester");
        mapViewPanel.add(lblWorcester, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 90, 20));

        lblNorthampton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblNorthampton.setForeground(new java.awt.Color(102, 102, 102));
        lblNorthampton.setText("Northampton");
        mapViewPanel.add(lblNorthampton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, 20));

        lblPittsfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblPittsfield.setForeground(new java.awt.Color(102, 102, 102));
        lblPittsfield.setText("Pittsfield");
        mapViewPanel.add(lblPittsfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, 20));

        lblSpringfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblSpringfield.setForeground(new java.awt.Color(102, 102, 102));
        lblSpringfield.setText("Springfield");
        mapViewPanel.add(lblSpringfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 90, 20));

        lblSalem.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblSalem.setForeground(new java.awt.Color(102, 102, 102));
        lblSalem.setText("Salem");
        mapViewPanel.add(lblSalem, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 90, 20));

        lblDedham.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblDedham.setForeground(new java.awt.Color(102, 102, 102));
        lblDedham.setText("Dedham");
        mapViewPanel.add(lblDedham, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 90, 20));

        lblTaunton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblTaunton.setForeground(new java.awt.Color(102, 102, 102));
        lblTaunton.setText("Taunton");
        mapViewPanel.add(lblTaunton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 90, 20));

        lblPlymouth.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblPlymouth.setForeground(new java.awt.Color(102, 102, 102));
        lblPlymouth.setText("Plymouth");
        mapViewPanel.add(lblPlymouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 90, 20));

        lblBarnstable.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblBarnstable.setForeground(new java.awt.Color(102, 102, 102));
        lblBarnstable.setText("Barnstable");
        mapViewPanel.add(lblBarnstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 90, 20));

        lblNantucket.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblNantucket.setForeground(new java.awt.Color(102, 102, 102));
        lblNantucket.setText("Nantucket");
        mapViewPanel.add(lblNantucket, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 70, 20));

        lblGreenfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblGreenfield.setForeground(new java.awt.Color(102, 102, 102));
        lblGreenfield.setText("Greenfield");
        mapViewPanel.add(lblGreenfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, 20));

        lblEdgartown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblEdgartown.setForeground(new java.awt.Color(102, 102, 102));
        lblEdgartown.setText("Edgartown");
        mapViewPanel.add(lblEdgartown, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 90, 20));

        lblCambridge.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblCambridge.setForeground(new java.awt.Color(102, 102, 102));
        lblCambridge.setText("Cambridge");
        mapViewPanel.add(lblCambridge, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 90, 20));

        lblAgent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/plane_normal.png"))); // NOI18N
        lblAgent1.setToolTipText("Agent 1");
        mapViewPanel.add(lblAgent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 30, 30));

        lblAgent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/plane_normal.png"))); // NOI18N
        lblAgent2.setToolTipText("Agent 2");
        mapViewPanel.add(lblAgent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 30, 30));

        lblAgent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/plane_normal.png"))); // NOI18N
        lblAgent3.setToolTipText("Agent 3");
        mapViewPanel.add(lblAgent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 30, 30));

        lblAgent4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/plane_normal.png"))); // NOI18N
        lblAgent4.setToolTipText("Agent 4");
        mapViewPanel.add(lblAgent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 30, 30));

        lblAgent5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/plane_normal.png"))); // NOI18N
        lblAgent5.setToolTipText("Agent 5");
        mapViewPanel.add(lblAgent5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 30, 30));

        lblMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/massachusetts-county-map.png"))); // NOI18N
        lblMap.setText("  ");
        mapViewPanel.add(lblMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1130, 640));

        mapViewScrollPane.setViewportView(mapViewPanel);

        getContentPane().add(mapViewScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1150, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromActionPerformed
        
        if(cmbFrom == null){
            return;
        }
        Location from = (Location) cmbFrom.getSelectedItem();
        
        cmbTo.removeAllItems();
        for(Location l : rm.getLocations())
            cmbTo.addItem(l);
        cmbTo.removeItem(from);
        
    }//GEN-LAST:event_cmbFromActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        
            Location from = (Location)cmbFrom.getSelectedItem();
            Location to = (Location)cmbTo.getSelectedItem();
           
            final int PLAY_TIME = getDistance(from, to)*20;
            
            final JLabel agent = getAvailableAgent();
            if(agent == null){
                System.out.println("No agent available");
                return;
            }
            
            final int startX = from.getCoordinate().x;
            final int startY = from.getCoordinate().y;

            final int targetX = to.getCoordinate().x;
            final int targetY = to.getCoordinate().y;
            
            final long startTime = System.currentTimeMillis();


            Timer timer = new Timer(30, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                                        
                    long duration = System.currentTimeMillis() - startTime;
                    float progress = (float)duration / (float)PLAY_TIME;
                    if (progress > 1f) {
                        progress = 1f;
                        ((Timer)(e.getSource())).stop();
                    }

                    int x = startX + (int)Math.round((targetX - startX) * progress);
                    int y = startY + (int)Math.round((targetY - startY) * progress);

                    agent.setLocation(x, y);
                    if(x == targetX && y == targetY){
                        availAgents.add(agent);
                        System.out.println( agent.getToolTipText() + " is available.");
                    }
                }
            });
            timer.start();
    }//GEN-LAST:event_btnRunActionPerformed

    public JLabel getAvailableAgent(){
        JLabel agent = availAgents.get(0);
        System.out.println( agent.getToolTipText()+ " on run.");
        availAgents.remove(0);
        return agent;
    }
    
    public int getDistance(Location p1, Location p2){
        
        int x1 = p1.getCoordinate().x;
        int y1 = p1.getCoordinate().y;
        int x2 = p2.getCoordinate().x;
        int y2 = p2.getCoordinate().y;
        
        return (int)Math.sqrt( (x1-x2)*(x1-x2) + (y1-y2)*(y1-y2) );
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JComboBox cmbFrom;
    private javax.swing.JComboBox cmbTo;
    private javax.swing.JPanel createAgentPanel;
    private javax.swing.JLabel lblAgent1;
    private javax.swing.JLabel lblAgent2;
    private javax.swing.JLabel lblAgent3;
    private javax.swing.JLabel lblAgent4;
    private javax.swing.JLabel lblAgent5;
    private javax.swing.JLabel lblBarnstable;
    private javax.swing.JLabel lblCambridge;
    private javax.swing.JLabel lblDedham;
    private javax.swing.JLabel lblEdgartown;
    private javax.swing.JLabel lblGreenfield;
    private javax.swing.JLabel lblMap;
    private javax.swing.JLabel lblNantucket;
    private javax.swing.JLabel lblNorthampton;
    private javax.swing.JLabel lblPittsfield;
    private javax.swing.JLabel lblPlymouth;
    private javax.swing.JLabel lblSalem;
    private javax.swing.JLabel lblSpringfield;
    private javax.swing.JLabel lblTaunton;
    private javax.swing.JLabel lblWorcester;
    private javax.swing.JPanel mapViewPanel;
    private javax.swing.JScrollPane mapViewScrollPane;
    private javax.swing.JTabbedPane monitoringTabbedPanel;
    // End of variables declaration//GEN-END:variables
}
